### ISSUE TITLE
[css-view-transitions-1] Enforce ::view-transition to be fixed position

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#102]
CSSWG added the following resolution(s):

> * `RESOLVED: Define "snapshot CB" as the current snapshot root rect, give it ICB behaviors so it captures all elements (preventing them from going higher)`

in https://github.com/w3c/csswg-drafts/issues/8505#issuecomment-1505587046

**Comment by vmpstr** [comment]
owner: bokan
comment: I think we need to make sure that 1. view-transition's containing block is always snapshot root, regardless of its own position property, and its descendants also use snapshot root if they aren't contained by view-transition

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1432630](https://crbug.com/1432630)

That is all that can be done here, closing issue.
