### ISSUE TITLE
[css-overflow-3] What clips scrollable overflow?

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#119]
CSSWG added the following resolution(s):

> * `RESOLVED: Explicitly define that overflow:clip does clip scrollable overflow`
> * `RESOLVED: clip and clip-path do not clip scrollable overflow`

in https://github.com/w3c/csswg-drafts/issues/8607#issuecomment-1533883987

**Comment by vmpstr** [comment]
comment: I think that's already the case in Chromium, but wanted to file an issue to double check.

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1442544](https://crbug.com/1442544)

That is all that can be done here, closing issue.
