### ISSUE TITLE
[css-view-transitions-1] Should mix-blend-mode be a part of the ua opacity animation?

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#138]
CSSWG added the following resolution(s):

> * `RESOLVED: Move mix-blend-mode behavior into the UA opacity animation`

in https://github.com/w3c/csswg-drafts/issues/8924#issuecomment-1591630313

**Comment by vmpstr** [comment]
owner: vmpstr

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1454863](https://crbug.com/1454863)

That is all that can be done here, closing issue.
