### ISSUE TITLE
[css-text-4] Don't provide a language parameter for word-boundary-detection

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#146]
CSSWG added the following resolution(s):

> * `RESOLVED: remove auto () from word-boundary-detection, add keyword to word-break for this functionality`

in https://github.com/w3c/csswg-drafts/issues/7193#issuecomment-1611772475

**Comment by vmpstr** [comment]
cc: kojii

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1458950](https://crbug.com/1458950)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: name it auto-phrase`
> * `RESOLVED: add a principle saying you should break within the phrase instead of overflowing`
> * `RESOLVED: If your phrase is too long you should break at a normal word boundry rather than overflow`

in https://github.com/w3c/csswg-drafts/issues/7193#issuecomment-1663101848
