### ISSUE TITLE
[css-view-transitions-2] Components participating in the transition need to leak info to embedding context

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#162]
CSSWG added the following resolution(s):

> * `RESOLVED: Have some way to assign a name to a VT and style differently based on it, details tbd`

in https://github.com/w3c/csswg-drafts/issues/8960#issuecomment-1640742768

**Comment by vmpstr** [comment]
comment: Need to experiment with startViewTransition(name) and then having that name appear in maybe ::view-transition(name) with the rest of the pseudos selectable through that (e.g. ::view-transition(name)::view-transition-group(foo))

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1466251](https://crbug.com/1466251)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: Add a 'TBD' argument to startViewTransition that takes a list of CSS identifiers, allow them to match against a pseudo-class which accepts a comma-separated (or) list of view transition names during which it matches`

in https://github.com/w3c/csswg-drafts/issues/8960#issuecomment-1719695337
