### ISSUE TITLE
[css-view-transitions-2] Cross-document View Transition when there is a UA transition

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#164]
CSSWG added the following resolution(s):

> * `RESOLVED: UAs may discard author transitions if they are providing their own`

in https://github.com/w3c/csswg-drafts/issues/8953#issuecomment-1640758636

**Comment by vmpstr** [comment]
owner: khushalsagar
comment: not sure if there's anything to do here?

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1469687](https://crbug.com/1469687)

That is all that can be done here, closing issue.
