### ISSUE TITLE
[css-animations-2] Make animation shorthand syntax future-proof

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#189]
CSSWG added the following resolution(s):

> * `RESOLVED: Add a new syntax for the animation shorthand where the animation-name comes first, followed by a slash, so that the new syntax (but not the old one) can accept animation-timeline and animation-composition in the shorthand.  Work out further details in issue.`

in https://github.com/w3c/csswg-drafts/issues/6946#issuecomment-1646065211

**Comment by bramus** [comment]
I manually created https://issues.chromium.org/issues/375388433 for this.
