### ISSUE TITLE
[css-anchor-position-1] Allow more properties in position fallbacks

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#212]
CSSWG added the following resolution(s):

> * `RESOLVED: add border, padding, and margin properties to position fallback rules`

in https://github.com/w3c/csswg-drafts/issues/9195#issuecomment-1690141172

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1475317](https://crbug.com/1475317)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: Remove border/padding.`

in https://github.com/w3c/csswg-drafts/issues/9195#issuecomment-1942297101
