### ISSUE TITLE
[css-anchor-1] Ability for a single element to have multiple anchor names

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#213]
CSSWG added the following resolution(s):

> * `RESOLVED: make the anchor-name property a comma-separated list of idents`

in https://github.com/w3c/csswg-drafts/issues/8837#issuecomment-1690145010

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1477313](https://crbug.com/1477313)

That is all that can be done here, closing issue.
