### ISSUE TITLE
[css-anchor-position-1] Grid-based anchoring syntax?

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#214]
CSSWG added the following resolution(s):

> * `RESOLVED: add a separate property (can bikeshed name in future), not merely a shorthand, but interacts with inset properties in current draft`
> * `RESOLVED: inset-area causes 'auto' keywords of inset to resolve to appropriate anchor() functions (TBD at computed or used value time)`

in https://github.com/w3c/csswg-drafts/issues/9145#issuecomment-1690207503

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1477314](https://crbug.com/1477314)

That is all that can be done here, closing issue.
