### ISSUE TITLE
[css-anchor-position-1] Alternative syntax for auto position fallback

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#215]
CSSWG added the following resolution(s):

> * `RESOLVED: accept proposal in the draft with details to be worked out over time`

in https://github.com/w3c/csswg-drafts/issues/9196#issuecomment-1690225805

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1475321](https://crbug.com/1475321)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * ``RESOLVED: adopt `position-try-*` with addition of inset-area into pos-try-opts``

in https://github.com/w3c/csswg-drafts/issues/9196#issuecomment-1942197882
