### ISSUE TITLE
[css-animations-2][css-transitions-2] Add animation object to animation/transition events.

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#223]
CSSWG added the following resolution(s):

> RESOLVED: Add an animation property to the animation*/transition* events that contains the relevant Animation object (CSSAnimation and CSSTransition respectively)

in https://github.com/w3c/csswg-drafts/issues/9010#issuecomment-1704330682

**Comment by bramus** [comment]
@chrishtr I think this should have been labeled as https://github.com/chromium-helper/csswg-resolutions/labels/crbug%3ABlink%3EAnimation

@vmpstr Will the bot pick this up after reopening, adding the label, and then closing again?

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1479139](https://crbug.com/1479139)

That is all that can be done here, closing issue.

**Comment by vmpstr** [comment]
> @vmpstr Will the bot pick this up after reopening, adding the label, and then closing again?

Yes, but it's more complicated if it already filed a bug before.

**Comment by bramus** [comment]
> it's more complicated if it already filed a bug before

Thankfully that was not the case here :)
