### ISSUE TITLE
[css-scoping][css-cascade] :scope in shadowy prelude-less @scope matches nothing

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#224]
CSSWG added the following resolution(s):

> RESOLVED: `@scope` without `<scope-start>` scopes to the shadow host instead of the shadow root.

in https://github.com/w3c/csswg-drafts/issues/9178#issuecomment-1704330959

**Comment by chrishtr** [comment]
owner:andruud@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1479127](https://crbug.com/1479127)

That is all that can be done here, closing issue.
