### ISSUE TITLE
[css-contain][css-anchor-position] Anchor names should be contained by style containment

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#225]
CSSWG added the following resolution(s):

> RESOLVED: Style containment contains anchor names

in https://github.com/w3c/csswg-drafts/issues/9100#issuecomment-1704331078

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1479126](https://crbug.com/1479126)

That is all that can be done here, closing issue.
