### ISSUE TITLE
[css-cascade-6] :scope and featureless elements

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#226]
CSSWG added the following resolution(s):

> RESOLVED: :scope can match the featureless shadow host when that host is the scoping element.

in https://github.com/w3c/csswg-drafts/issues/9025#issuecomment-1704331145

**Comment by chrishtr** [comment]
owner:andruud@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1479125](https://crbug.com/1479125)

That is all that can be done here, closing issue.
