### ISSUE TITLE
[css-anchor-position-1] Better reusability of anchor names

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#243]
CSSWG added the following resolution(s):

> * ``RESOLVED: Add an `anchor-scope` property``

in https://github.com/w3c/csswg-drafts/issues/9045#issuecomment-1721297734

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1483283](https://crbug.com/1483283)

That is all that can be done here, closing issue.
