### ISSUE TITLE
[css-anchor-position-1] Define interaction with the cascade in `@try`

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#244]
CSSWG added the following resolution(s):

> * `RESOLVED: !important must win and the issue of putting @try properties in their place in the cascade will be investigated`

in https://github.com/w3c/csswg-drafts/issues/9149#issuecomment-1721333819

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1483286](https://crbug.com/1483286)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: fallback styles live in a new "Position Fallback Origin". They revert like Animation styles (back to User origin)`

in https://github.com/w3c/csswg-drafts/issues/9149#issuecomment-2009875182
