### ISSUE TITLE
[css-anchor-1] Need ability to say "don't render" when anchor is off-screen

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#247]
CSSWG added the following resolution(s):

> * `RESOLVED: we add something to deal with clipping in this context`

in https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1721382237

**Comment by chrishtr** [comment]
owner:xiaochengh@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1483282](https://crbug.com/1483282)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED:  Add position-visibility as proposed in the issue with concerns noted as issues in the draft, to the editors draft *after* publication of working draft.`

in https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1994765991
