### ISSUE TITLE
[css-display-4] Do we need `reading-order: <integer>` or should `reading-order: auto` be allowable in all grid or flex layouts?

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#248]
CSSWG added the following resolution(s):

> * `RESOLVED: add reading-order-items into the ED and remove reading-order:<integer>`

in https://github.com/w3c/csswg-drafts/issues/8589#issuecomment-1721504153

**Comment by chrishtr** [comment]
owner:chrishtr@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1483317](https://crbug.com/1483317)

That is all that can be done here, closing issue.
