### ISSUE TITLE
[css-contain-2] API to expose skipped content state

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#260]
CSSWG added the following resolution(s):

> * `RESOLVED: Extend checkVisibility to expose content-visibility: auto state`

in https://github.com/w3c/csswg-drafts/issues/9474#issuecomment-1768906480

**Comment by vmpstr** [comment]
owner:jarhar

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1493775](https://crbug.com/1493775)

That is all that can be done here, closing issue.
