### ISSUE TITLE
[cssom-view] checkVisibility options have inconsistent naming schemes

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#264]
CSSWG added the following resolution(s):

> * `RESOLVED: don’t rename but define pattern for arguments and add aliases`

in https://github.com/w3c/csswg-drafts/issues/9487#issuecomment-1779664600

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: Adopt the naming scheme for future values and as aliases for existing values`

in https://github.com/w3c/csswg-drafts/issues/9487#issuecomment-1789812122

**Comment by vmpstr** [comment]
owner: vmpstr

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1500731](https://crbug.com/1500731)

That is all that can be done here, closing issue.
