### ISSUE TITLE
[css-view-transitions-2] resolve on descriptor/parameter names

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#274]
CSSWG added the following resolution(s):

> * `RESOLVED: type can accept any idents, except 'none' or '-ua-' prefixes`
> * `RESOLVED: at-rule is @view-transition, descriptors are 'navigation' and 'type', 'navigation' grammar is "auto | none" ('type' grammar already resolved)`

in https://github.com/w3c/csswg-drafts/issues/9534#issuecomment-1802364085

**Comment by vmpstr** [comment]
owner: vmpstr

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1500714](https://crbug.com/1500714)

That is all that can be done here, closing issue.
