### ISSUE TITLE
[css-zoom?] Zoom and CSSOM

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#285]
CSSWG added the following resolution(s):

> * `RESOLVED: getComputedStyle() returns unzoomed value`
> * `RESOLVED: APIs that return bounding boxes such as getClientRects and ResizeObserver and IntersectionObserver return values in page-global px units`
> * `RESOLVED: s/ResizeObserver/getBoundingClientRect/`

in https://github.com/w3c/csswg-drafts/issues/9398#issuecomment-1832386800

**Comment by chrishtr** [comment]
owner:chrishtr@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1506210](https://crbug.com/1506210)

That is all that can be done here, closing issue.
