### ISSUE TITLE
[css-zoom?] Zoom and inheritance. 

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#286]
CSSWG added the following resolution(s):

> * `RESOLVED: font-size is not special wrt zoom`
> * `RESOLVED: All computed absolute lengths are zoomed when inheriting`

in https://github.com/w3c/csswg-drafts/issues/9397#issuecomment-1832408851

**Comment by chrishtr** [comment]
owner:chrishtr@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1506209](https://crbug.com/1506209)

That is all that can be done here, closing issue.
