### ISSUE TITLE
[css-view-transitions-1] Disallow the name `auto` as `view-transition-name`

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#305]
CSSWG added the following resolution(s):

> * `RESOLVED: disallow auto for view-transitions-name/view-transitions`

in https://github.com/w3c/csswg-drafts/issues/9639#issuecomment-1864885443

**Comment by vmpstr** [comment]
owner: vmpstr

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1513460](https://crbug.com/1513460)

That is all that can be done here, closing issue.
