### ISSUE TITLE
[mediaqueries-5] Add display-mode for document picture-in-picture

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#318]
CSSWG added the following resolution(s):

> * `RESOLVED: Adopt picture-in-picture media query`

in https://github.com/w3c/csswg-drafts/issues/9260#issuecomment-1896248306

**Comment by chrishtr** [comment]
Might want to prioritize this given we shipped document PiP

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1520690](https://crbug.com/1520690)

That is all that can be done here, closing issue.
