### ISSUE TITLE
[css-mediaqueries] Inverted-colors media feature can cause problems on semi-transparent images.

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#319]
CSSWG added the following resolution(s):

> * `RESOLVED: Remove requirement for the ua stylesheet rule for inverted-colors`

in https://github.com/w3c/csswg-drafts/issues/9674#issuecomment-1896256196

**Comment by chrishtr** [comment]
Might need a UA style sheet change?

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1520691](https://crbug.com/1520691)

That is all that can be done here, closing issue.
