### ISSUE TITLE
[css-inline-3] text-box-trim accumulation

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#327]
CSSWG added the following resolution(s):

> * `RESOLVED: Choosing the innermost for textbox:trim for most requested trim metric.`

in https://github.com/w3c/csswg-drafts/issues/5426#issuecomment-1908631337

**Comment by chrishtr** [comment]
owner:kojii@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1521463](https://crbug.com/1521463)

That is all that can be done here, closing issue.
