### ISSUE TITLE
[css-inline-3] text-box-trim vs fragmentation 

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#328]
CSSWG added the following resolution(s):

> * `RESOLVED: Should text-box-trim apply at fragmentation breaks, depend on the box-decoration-break property`

in https://github.com/w3c/csswg-drafts/issues/5335#issuecomment-1908655635

**Comment by chrishtr** [comment]
owner:kojii@chromium.org

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1521464](https://crbug.com/1521464)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: if you apply text-box-trim to a multicol container, it applies to the first formatted line of each column, and analogous for the last`

in https://github.com/w3c/csswg-drafts/issues/5335#issuecomment-2380160677
