### ISSUE TITLE
[css-multicol] What is the max-content width of a muticol container with only column-width:<length>

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#334]
CSSWG added the following resolution(s):

> * `RESOLVED:  Add window-focus: active or none matching behavior of javascript in imprint behavior and matching`

in https://github.com/w3c/csswg-drafts/issues/9103#issuecomment-1933178238

**Comment by astearns** [comment]
(this was an unrelated stray bit from a previous issue’s discussion, and I have deleted the comment)

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: Define the behavior we want with forced breaks (column-width * (forced-break-count + 1)), with the forced-break situation at risk, in multicol L2`

in https://github.com/w3c/csswg-drafts/issues/9103#issuecomment-1939833852
