### ISSUE TITLE
[view-transitions-2] Add method to get all animations of a ViewTransition object

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#480]
CSSWG added the following resolution(s):

> * `RESOLVED: Add a pseudoElement option to the element.getAnimations() dict arg. subtree:true/false acts on that pseudo as the root`
> * `RESOLVED: Add .transitionRoot readonly property to VT object, reflectring the element hosting the VT.`

in https://github.com/w3c/csswg-drafts/issues/9908#issuecomment-2165621635

**Comment by chromium-helper** [comment]
I have filed [issues.chromium.org/346973998](https://issues.chromium.org/346973998)

 That is all that can be done here, closing issue.

**Comment by bramus** [comment]
@vmpstr Looking at the resolutions and what the helper did: maybe the helper should make an issue per resolution instead of per csswg issue? Here they are two actionable items (in different Chromium components)

**Comment by bramus** [comment]
FYI: I manually created https://issues.chromium.org/347506559 for the 1st resolution.

**Comment by vmpstr** [comment]
Yeah that's probably a good idea.
