### ISSUE TITLE
[scroll-animations-1] naming the initial value of animation-range

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#67]
CSSWG added the following resolution(s):

> * `RESOLVED: animation-range's initial value is the keyword "normal"`

in https://github.com/w3c/csswg-drafts/issues/8406#issuecomment-1476429430

**Comment by vmpstr** [comment]
This is causing a CF error: body: Error parsing request: Failed to load JSON: Expecting ',' delimiter: line 12 column 128 (char 577).

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1426544](https://crbug.com/1426544)

That is all that can be done here, closing issue.
