### ISSUE TITLE
[scroll-animations-1] Allow optional `<percentage>` in `animation-range-*`

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#70]
CSSWG added the following resolution(s):

> * `RESOLVED:  Make <percentage> optional in animation-range-start/end, defaulting to 0%/100%`
> * `RESOLVED: When specifying "animation-range: foo X%", set the -range-end to "foo 100%" (staying in same phase, just setting to end)`

in https://github.com/w3c/csswg-drafts/issues/8438#issuecomment-1476465774

**Comment by vmpstr** [comment]
Suspecting double quotes cause CF error.

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1426562](https://crbug.com/1426562)

That is all that can be done here, closing issue.
