### ISSUE TITLE
[css-color-4] Allow out-of-gamut HSL/HWB colors (previously "Move gamut mapping to a future spec")

### ISSUE THREAD

**Issue by chromium-helper** [chromium-helper/csswg-resolutions#83]
CSSWG added the following resolution(s):

> * `RESOLVED: allow out-of-gamut HSL and HWB colors`

in https://github.com/w3c/csswg-drafts/issues/8444#issuecomment-1479912735

**Comment by chromium-helper** [comment]
I have filed [crbug.com/1427304](https://crbug.com/1427304)

That is all that can be done here, closing issue.

**Comment by chromium-helper** [comment]
CSSWG added the following resolution(s):

> * `RESOLVED: Make color-mix() and RCS using rgb, hsl and hwb return round-trippable, unbounded results in color(srgb ...)`

in https://github.com/w3c/csswg-drafts/issues/8444#issuecomment-1542537362

**Comment by chrishtr** [comment]
Issue: 1427304
